### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by jolouvet** [lanl-ansi/MomentOpt.jl#24]
I was wondering if there are any plans to update MomentOpt to support more recent releases of its dependencies ?

**Comment by ccoffrin** [comment]
hi @jolouvet.  There are no plans to update MomentOpt and given that the last commit was 4 years ago, I suspect any further maintenance is unlikely.  We will put in our best effort to merge maintenance pull requests.

**Comment by blegat** [comment]
I started part of the update in https://github.com/lanl-ansi/MomentOpt.jl/pull/23/, the follow up is https://github.com/lanl-ansi/MomentOpt.jl/pull/25

**Comment by jolouvet** [comment]
Thank you!
